# test_environment/docker/docker-compose.yml
# Changed subnet from 172.20.0.0/16 to 10.0.0.0/16
name: honeypot-test-environment

networks:
  honeypot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16    # CHANGED: from 172.20.0.0/16

services:
  smart-camera:
    build: 
      context: ./smart-camera
      dockerfile: Dockerfile
    container_name: smart-camera
    networks:
      honeypot_network:
        ipv4_address: 10.0.0.2   # CHANGED: from 172.20.0.2
    ports:
      - "8080:80"
    restart: unless-stopped

  iot-gateway:
    build:
      context: ./gateway-config
      dockerfile: Dockerfile
    container_name: iot-gateway
    networks:
      honeypot_network:
        ipv4_address: 10.0.0.3   # CHANGED: from 172.20.0.3
    ports:
      - "8081:80"
    restart: unless-stopped

  analysis-system:
    build:
      context: ../..
      dockerfile: test_environment/docker/analysis/Dockerfile
    container_name: analysis-system
    networks:
      honeypot_network:
        ipv4_address: 10.0.0.4   # CHANGED: from 172.20.0.4
    volumes:
      - ../../src:/app/src
      - ../../test_environment:/app/test_environment
    depends_on:
      - smart-camera
      - iot-gateway